### ISSUE TITLE
Nesting and other props

### ISSUE THREAD

**Issue by jide** [nachoaIvarez/flexbox-react#1]
Hey,

This is pretty cool, but I did not find a way to have a flexbox inside a flexitem take 100% of its height : 

``` js
      <Flexbox flexDirection='column' height='100%'>
        <FlexItem flexGrow={ 1 }>
          <Flexbox flexDirection='column' minHeight='100%'>
            Hey
          </Flexbox>
        </FlexItem>
        <FlexItem>
          Hoy
        </FlexItem>
      </Flexbox>
```

There is no way to make the nested Flexbox fill its parent.

Another thought: I see we can pass a "className" prop, but it would be really nice to be able to pass any arbitrary props (like "style") : 
https://github.com/nachoaIvarez/flexbox-react/blob/master/src/FlexItem.jsx#L27

A better way would be to split props between those regarding flex and other props and apply all other props to the div so that we can have control over them : 

``` js
  render() {
    const { alignSelf, flex, flexBasis, ...props } = this.props // skipping most props here for brievety

    return (
      <div style={this.styles()} { ...props }>
        {this.props.children}
      </div>
    );
  }
```

**Comment by jide** [comment]
Sorry I hit "enter" accidentally so you may have been noticed of an unfinished comment.

**Comment by nachoaIvarez** [comment]
Hey @jide! I tried your code, here's the thing. Your parent `Flexbox` component has `height="100%"` that means that if its parent node has no declared `height` that rule won't do anything (nothing related to `flexbox-react`, that's the way % heights and widths work). If you try `height="50vh"` (half of the viewport height), or  `height="400px"` for example, it works. Anything that is fixed and not relative. If you want relatives to work, set a height on the parent! 
<img width="798" alt="screen shot 2016-04-26 at 1 53 41 pm" src="https://cloud.githubusercontent.com/assets/7253814/14826903/53a5733a-0bb6-11e6-87be-75cdf062cd09.png">

Regarding the code styling, I see your point, I think that could be a good idea! Feel free to leave a PR, if you don't want to, I'll reviewing that code soon. Thanks!

**Comment by jide** [comment]
Hey @nachoaIvarez,

In fact the Flexbox element is in a 100% div, which is in a 100% body, so I thought it should work.

I used to have a manually styled div being both a flex item and a flex container, which makes me wondering if having 2 components types is relevant. Having only one would probably make the whole thing less obvious though.

Regarding the props thing, it's not a question of coding style, it's about being able to pass any prop to the underlying div, like "id", "style", "onClick", whatever... I may submit a PR for this.

**Comment by nachoaIvarez** [comment]
Sure @jide, more than welcome!
