### ISSUE TITLE
Example of how to hndle transitions and animations

### ISSUE THREAD

**Issue by GilbertMizrahi** [nachoaIvarez/flexbox-react#12]
Thanks for this package.
How you would do animations when adding or removing flex items?

**Comment by nachoaIvarez** [comment]
Like any other `div` or component! Here you have some good reads and tools, nothing specific about `flexbox-react`:
 https://facebook.github.io/react/docs/animation.html
https://github.com/chenglou/react-motion
https://github.com/juliangarnier/anime
