### ISSUE TITLE
Module build failed: SyntaxError: Unexpected token (11:49)

### ISSUE THREAD

**Issue by TheoMer** [nachoaIvarez/flexbox-react#15]
So I'm getting an unexpected token error when utilising `list-style`:

`<Flexbox margin="0" padding="0" style={{ list-style: 'none' border: '1px solid black' }}>`

What's the issue here?

See attached image for full error breakdown.

![list-style error](https://cloud.githubusercontent.com/assets/15969262/18144609/5cf101c6-6fbf-11e6-9cd4-7b80112eed3b.jpg)

**Comment by nachoaIvarez** [comment]
You are using `list-style` as a key for a JavaScript object. Use `'list-style'` or `listStyle` instead. That's a syntax error in JS and has nothing to do with `flexbox-react` 😄

**Comment by TheoMer** [comment]
@nachoaIvarez Thanks for the info. No errors are being generated now :-)

The only issue I am having is that my list is not rendering from items stacked one on top of another (column), to a display flex (row) with no bullet points. The bullet points of <`li>` still remain, only the black border renders correctly.

`<Flexbox element="nav" margin="0" padding="0" style={{ 'list-style': 'none', border: '1px solid black' }}>`
      `<ul>`
        `<li>`
          `<Link to="/">`
            `This`
          `</Link>`
        `</li>`
        `<li>`
          `<Link activeClassName="active" to="/firebase">`
            `That`
          `</Link>`
       `</li>`
     `</ul>`

As the opening tag should render as:

`<nav style="display: flex;...">` 

I expected the list to be displayed horizontally, but is not. What am I overlooking?

**Comment by nachoaIvarez** [comment]
Take a look at [`flexDirection` ](https://developer.mozilla.org/en/docs/Web/CSS/flex-direction)!

**Comment by TheoMer** [comment]
@nachoaIvarez Not to worry, I got it working now. 

I needed to lose the `<ul>` tag, and specify `<Flexbox element="ul">` instead.

Many thanks for your time

**Comment by nachoaIvarez** [comment]
No problem! 😄
