### ISSUE TITLE
Question: @media attribute of style tag, not rendering as expected

### ISSUE THREAD

**Issue by TheoMer** [nachoaIvarez/flexbox-react#16]
@nachoaIvarez So,I'm wishing to `wrap` a menu list once the screen pixel width reaches a predetermined size, and  have applied the following logic, without success. No errors/warnings are being generated. What am I overlooking?:

`<Flexbox element="nav"`
`minWidth="100vw"`
`margin="0"`
`padding="0"`
`style={{ '@media all and (maxWidth: 1000px)': {flexWrap: 'wrap'} }}>`

`<navigation menu />`

`</Flexbox>`

Many thanks in advance.

P.S. Is this project on Gitter, which would be a more apt place to submit general queries?

**Comment by nachoaIvarez** [comment]
You should take a look at this: https://github.com/contra/react-responsive!

There's no gitter currently! Maybe in the future?
