### ISSUE TITLE
Exclude @types/react & @types/react-dom from dependencies

### ISSUE THREAD

**Issue by panjiesw** [nachoaIvarez/flexbox-react#19]
Hi,
This is a very useful component and comes with Typescript definition included. But I think it'll be hard for users if you include `@types/react` & `@types/react-dom` as this package dependencies. 

Mostly users will have those dependencies included already in their project and so will create duplicate Typescript definitions if their versions are different than what's required in this package, causing compile errors.

Same as with `react`, it'll be safer to include them as peerDependencies. That way, if a user install this package without already having them, they will see a warning. Or, don't include them at all so non-typescript user won't have to forcibly include them if they don't need it.

What do you think?

**Comment by nachoaIvarez** [comment]
I agree. Note that `react` [is included in `peerDependencies`](https://github.com/nachoaIvarez/flexbox-react/blob/master/package.json#L40-L41) and `devDependencies` (for development purposes) but not in `dependencies`, so it is not an actual dependency that may cause conflicts or may end up in a bundle. You're right about your concerns about those Typescript dependencies. I would add that they are irrelevant for those users not using typescript. I was thinking of putting them as [optionalDependencies](https://docs.npmjs.com/files/package.json#optionaldependencies). I'm submitting a PR with those changes. Thanks for the feedback @panjiesw!

**Comment by nachoaIvarez** [comment]
v4.1.1 is out with fixes.
