### ISSUE TITLE
Wrapping an input will cause the input to loose focus after onChange

### ISSUE THREAD

**Issue by doostin** [nachoaIvarez/flexbox-react#28]
Here is an example of a component that will break the input's onChange:

    class NewSlideButton extends Component {
      constructor(props) {
        super(props);
        this.state = {
          title: ''
        };
        this.handleClick = this.handleClick.bind(this);
        this.handleChange = this.handleChange.bind(this);
      }

      handleChange({ target: { value } }) {
        this.setState({ title: value });
      }

      handleClick() {
        this.props.actions.createNewSlide(this.state.title);
      }

      render() {
        return (
          <Flexbox
            key="input"
            className="add-new-slide"
            marginBottom="10px"
            height="40px"
            flexDirection="row"
          >
            <input
              type="text"
              className="add-new-slide__title-input"
              value={this.state.title}
              placeholder="Enter slide title"
              onChange={this.handleChange}
            />
            <Flexbox
              alignItems="center"
              justifyContent="center"
              className="add-new-slide__button"
              onClick={this.handleClick}
            >Add slide</Flexbox>
          </Flexbox>
        );
      }
    }

**Comment by nachoaIvarez** [comment]
@doostin: Checkout v4.3.1. Thanks @hoppula for your PR!
