### ISSUE TITLE
MediaQueries?

### ISSUE THREAD

**Issue by songvc** [nachoaIvarez/flexbox-react#3]
Thanks for the awesome library. I was trying to blend inline flexbox css declarations into my components and found your library to be a lot more intuitive and easy-to-read than other flexbox libraries out there that try to use Boostrappy namespaces (grid, rows, columns etc..).

I have one feature request. I am wondering if you can add media queries as potential prop inputs(by adding them into list of required PropTypes?) I am trying to make my flexbox layout respond to different screen size. I am experimenting with Radium where you can add custom media query declarations injected into inline style props. 

I am thinking of potential use cases like this:
If the screen size is mobile, flex direction changes from column to row so layout does column-dropping.

``` javascript
const medaQueries = {
  "@media (max-Width: 960px)": {
    "flexDirection": "column"
    // other CSS
  },
  // other break points//
}
```

``` javascript
<Flexbox style={mediaQueries} flexDirection="row" flexWrap="wrap" minHeight="100%" width="100%">
 // Flex items
</Flexbox>
```

Any other good solutions can you think of other than this? Let me know. Thanks

**Comment by nachoaIvarez** [comment]
Thanks for your feedback @songvc. I completely agree it would be awesome to have a way to gracefully handle responsive layouts with MediaQueries. 

Currently, the tool supports inline styles, but the flexbox-specific ones get overridden when the component props. That would be solved putting the `style` spread operator at the bottom of the stylesheet we generate (so it overrides the props)?

If you want to submit a PR feel free to do it, if not I will add that soon. Thanks!
