### ISSUE TITLE
4.3.0 kills my app

### ISSUE THREAD

**Issue by ggascoigne** [nachoaIvarez/flexbox-react#30]
I was successfully using 4.2.1 in a create-react-app based app.  I just upgraded it to use 4.3.0, this brought in a number of upgraded dependencies.

```sh
├─ buffer@5.0.5
├─ css-color-list@0.0.1
├─ css-color-names@0.0.1
├─ css-to-react-native@1.0.6
├─ discontinuous-range@1.0.0
├─ fbjs@0.8.9
├─ flexbox-react@4.3.0
├─ glamor@2.20.24
├─ is-function@1.0.1
├─ is-plain-object@2.0.1
├─ isobject@1.0.2
├─ nearley@2.8.0
├─ nomnom@1.6.2
├─ railroad-diagrams@1.0.0
├─ randexp@0.4.5
├─ ret@0.1.14
└─ styled-components@1.4.4
```

We are using redux and every time a redux action gets sent it looks like the complete dom is reloaded, and in this case changed, by the addition of  an ever increasing number of empty <style type="text/css"></style> blocks being loaded in my <head> block, then the app becomes completely unresponsive and I have to kill it.

I'll keep digging.

**Comment by nachoaIvarez** [comment]
Checkout v4.3.1! Thanks @hoppula for your help.

**Comment by ggascoigne** [comment]
That fixed it, thank you.  Sorry I missed #26 and created a vague duplicate.
